# This file is for local development overrides
# Create a .env file in the project root with your actual API keys
# Example .env file:
# GROQ_API_KEY=your_groq_api_key_here
# GOOGLE_GENERATIVE_AI_API_KEY=your_google_api_key_here

services:
  app-dev:
    build:
      args:
        - GROQ_API_KEY=${GROQ_API_KEY:-}
        - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
    environment:
      - VITE_GROQ_API_KEY=${GROQ_API_KEY:-}
      - VITE_GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}

  app-prod:
    build:
      args:
        - GROQ_API_KEY=${GROQ_API_KEY:-}
        - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
    environment:
      - VITE_GROQ_API_KEY=${GROQ_API_KEY:-}
      - VITE_GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY:-}
